### ISSUE TITLE
Query string containing embedded ampersand are not properly encoded

### ISSUE THREAD

**Issue by renuyadav** [scssyworks/deparam.js#16]
Issue is if the string contains embedded ampersand then it is treated as a separate query parameter though it should be part of the previous parameter value.

e.g if we enter serialized form data query like str="renu&yadav" it will become renu%yadav which is ideally correct. But in the code you are using decodeURIComponent to decode the string so it's converting embedded  ampersand to '&'. So when we submit the form  its treated as separate query parameter and values are submitted like below in n/w tab :

str = renu
yadav 

I  have done the fix for this, will raise PR to you shortly.

Thank you!!! 

Regards
Renu Yadav

**Comment by scssyworks** [comment]
Hi @renuyadav 
Please use the latest version of library which should resolve your issue.
