### ISSUE TITLE
Provide an ESM version that does not include ES6 language features

### ISSUE THREAD

**Issue by sabberworm** [scssyworks/deparam.js#17]
It’s cool that you provide a `"module"` entrypoint that uses an ES-module export. But unfortunately it also uses some newer ES features like arrow functions that IE 11 doesn’t support. This means when I use a bundler like webpack or rollup that understands the `module` field, I get bundled code that IE 11 doesn’t support.

Using advanced language features is not what the `module` field is for. For example, the rollup guide on pkg.module [states](https://github.com/rollup/rollup/wiki/pkg.module):

> `pkg.module` will point to a module that has _ES2015 module syntax_ but otherwise _only syntax features that the target environments support_.

[and](https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features)

>[…] If you're using things like arrow functions and classes (or more exotic features like decorators and object spread), you should transpile them if you want your library to work in environments that don't support those features. Otherwise, whoever uses your library will have to transpile it themselves, including configuring their transpiler to handle your code, which might involve esoteric transforms and conflicting versions of Babel.
>
> It's a frequent source of frustration. **Be a responsible library author** and ship code that actually runs in the environments you support!

(emphasis mine)

**Comment by scssyworks** [comment]
Thanks for your contribution @sabberworm 
Please install the latest version and let me know if you're still facing any issues.
